src/unit4/config/routes.rb
Rails.application.routes.draw do
  resources :dollars

end

src/unit4/app/models/book.rb
class Book < ActiveRecord::Base
end

src/unit4/app/models/dollar.rb
class Dollar < ActiveRecord::Base
end

src/unit4/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

src/unit4/app/controllers/dollars_controller.rb
class DollarsController < ApplicationController
  before_action :set_dollar, only: [:show, :edit, :update, :destroy]

  # GET /dollars
  # GET /dollars.json
  def index
    @dollars = Dollar.all
  end

  # GET /dollars/1
  # GET /dollars/1.json
  def show
  end

  # GET /dollars/new
  def new
    @dollar = Dollar.new
  end

  # GET /dollars/1/edit
  def edit
  end

  # POST /dollars
  # POST /dollars.json
  def create
    @dollar = Dollar.new(dollar_params)

    respond_to do |format|
      if @dollar.save
        format.html { redirect_to @dollar, notice: 'Dollar was successfully created.' }
        format.json { render :show, status: :created, location: @dollar }
      else
        format.html { render :new }
        format.json { render json: @dollar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dollars/1
  # PATCH/PUT /dollars/1.json
  def update
    respond_to do |format|
      if @dollar.update(dollar_params)
        format.html { redirect_to @dollar, notice: 'Dollar was successfully updated.' }
        format.json { render :show, status: :ok, location: @dollar }
      else
        format.html { render :edit }
        format.json { render json: @dollar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dollars/1
  # DELETE /dollars/1.json
  def destroy
    @dollar.destroy
    respond_to do |format|
      format.html { redirect_to dollars_url, notice: 'Dollar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dollar
      @dollar = Dollar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dollar_params
      params.require(:dollar).permit(:value, :condition, :president)
    end
end

src/unit4/app/helpers/application_helper.rb
module ApplicationHelper
end

src/unit4/app/helpers/dollars_helper.rb
module DollarsHelper
end

src/unit4/app/views/dollars/_form.html.erb
<%= form_for(@dollar) do |f| %>
  <% if @dollar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dollar.errors.count, "error") %> prohibited this dollar from being saved:</h2>

      <ul>
      <% @dollar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value %><br>
    <%= f.number_field :value %>
  </div>
  <div class="field">
    <%= f.label :condition %><br>
    <%= f.text_field :condition %>
  </div>
  <div class="field">
    <%= f.label :president %><br>
    <%= f.text_field :president %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

src/unit4/app/views/dollars/edit.html.erb
<h1>Editing Dollar</h1>

<%= render 'form' %>

<%= link_to 'Show', @dollar %> |
<%= link_to 'Back', dollars_path %>

src/unit4/app/views/dollars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Dollars</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th>Condition</th>
      <th>President</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dollars.each do |dollar| %>
      <tr>
        <td><%= dollar.value %></td>
        <td><%= dollar.condition %></td>
        <td><%= dollar.president %></td>
        <td><%= link_to 'Show', dollar %></td>
        <td><%= link_to 'Edit', edit_dollar_path(dollar) %></td>
        <td><%= link_to 'Destroy', dollar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dollar', new_dollar_path %>

src/unit4/app/views/dollars/new.html.erb
<h1>New Dollar</h1>

<%= render 'form' %>

<%= link_to 'Back', dollars_path %>

src/unit4/app/views/dollars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @dollar.value %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @dollar.condition %>
</p>

<p>
  <strong>President:</strong>
  <%= @dollar.president %>
</p>

<%= link_to 'Edit', edit_dollar_path(@dollar) %> |
<%= link_to 'Back', dollars_path %>

src/unit4/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Unit4</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>